version: "3.1"
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev/:/etc/nginx/
    restart: "no"
  app:
    build:
      context: .
      dockerfile: Dockerfile-app-dev
    restart: "no"
  mysql:
    restart: "no"
  nodejs:
    restart: "no"
networks:
  mlo:
  nginx-load-balancer:
